[build]
  command = "npm run build"  # Replace with your build command if applicable

[[redirects]]
  from = "/Age_calculator/*"           # Define the URL path for dir1
  to = "Age_calculator/:splat"         # Specify the directory path for dir1
  status = 200

[[redirects]]
  from = "/Wall-clock/*"           # Define the URL path for dir2
  to = "Wall-clock/:splat"         # Specify the directory path for dir2
  status = 200

[build]
  publish = "/"              # Specify the root directory as the publish directory
